### PR TITLE
Provide the latest scroll index to DraggableScrollbar

### LINKED ISSUE #2: [Feature Request] Ability to provide a label text builder
Firstly, thanks for the great library, it has been a blessing!

Now, while using the `DraggableScrollbar`, I'd like to provide a label text next to the "thumb".

The original library exposes a [`labelTextBuilder`](https://github.com/fluttercommunity/flutter-draggable-scrollbar#arrows-thumb--label) which does this. Would it be possible for you to expose something similar?

Thanks again!

### PR DESCRIPTION
**Pull request by vishnukvmd**
Fixes #2 .

### CODE REVIEW

**Comment by deakjahn** [comment]
OK, I added a couple of changes `pedantic` called for and pushed the whole as 2.0.1 to Pub.dev. Thanks.

**Comment by deakjahn** [comment]
By the way, do you, by any chance, have a simple (or stripped down) custom thumb that could be placed in the README to show your approach? It would be nice...

**Comment by vishnukvmd** [comment]
A stripped down version would be:

```dart
thumbBuilder: (Color backgroundColor, Color drawColor, double height, int index) {
  return ScrollBarThumb(backgroundColor, drawColor, height, index.toString());
}
```

where `ScrollBarThumb` is
```dart

class ScrollBarThumb extends StatelessWidget {
  final backgroundColor;
  final drawColor;
  final height;
  final title;

  const ScrollBarThumb(
    this.backgroundColor,
    this.drawColor,
    this.height,
    this.title, {
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.end,
      children: [
        Container(
          padding: EdgeInsets.all(8),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(10),
            color: Colors.white.withOpacity(0.8),
          ),
          child: Text(
            title,
            style: TextStyle(
              color: Colors.black,
              backgroundColor: Colors.transparent,
              fontSize: 14,
            ),
          ),
        ),
        Padding(
          padding: EdgeInsets.all(2),
        ),
        CustomPaint(
          foregroundPainter: _ArrowCustomPainter(drawColor),
          child: Material(
            elevation: 4.0,
            child: Container(
                constraints: BoxConstraints.tight(Size(height * 0.6, height))),
            color: backgroundColor,
            borderRadius: BorderRadius.only(
              topLeft: Radius.circular(height),
              bottomLeft: Radius.circular(height),
              topRight: Radius.circular(4.0),
              bottomRight: Radius.circular(4.0),
            ),
          ),
        ),
      ],
    );
  }
}

class _ArrowCustomPainter extends CustomPainter {
  final Color drawColor;

  _ArrowCustomPainter(this.drawColor);

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..isAntiAlias = true
      ..style = PaintingStyle.fill
      ..color = drawColor;
    const width = 12.0;
    const height = 8.0;
    final baseX = size.width / 2;
    final baseY = size.height / 2;

    canvas.drawPath(
        trianglePath(Offset(baseX - 4.0, baseY - 2.0), width, height, true),
        paint);
    canvas.drawPath(
        trianglePath(Offset(baseX - 4.0, baseY + 2.0), width, height, false),
        paint);
  }

  static Path trianglePath(
      Offset offset, double width, double height, bool isUp) {
    return Path()
      ..moveTo(offset.dx, offset.dy)
      ..lineTo(offset.dx + width, offset.dy)
      ..lineTo(offset.dx + (width / 2),
          isUp ? offset.dy - height : offset.dy + height)
      ..close();
  }
}

```

**Comment by deakjahn** [comment]
Excellent, thank you, I put it into the README.

**Pull request merged**
